# Generated by Django 3.2.7 on 2024-08-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegasapp', '0002_auto_20240819_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
