# Generated by Django 3.2.7 on 2024-08-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegasapp', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
